### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ItsDavehere** [antony-jr/instagram-py#21]
Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'socks'

**Comment by antony-jr** [comment]
@ItsDavehere Looks like a dependency error , not on the instagram-py side though. Use the **Instagram-Py Portable** version to use instagram-py without any setup , You don't even need tor and python installed.. Just a single command. Here is how you do it -> https://www.youtube.com/watch?v=nNfSyI_Q9SM 

**Note** : Don't start tor server when you are using the portable version , You can use it in a live boot too.... Any linux distro.
